spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/api/users/**
              filters:
                - StripPrefix=2
            - id: analyses
              uri: ${ANALYSIS_SERVICE_URL}
              predicates:
                - Path=/api/analyses/**
              filters:
                - StripPrefix=2
            - id: locations
              uri: ${LOCATION_SERVICE_URL}
              predicates:
                - Path=/api/locations/**
              filters:
                - StripPrefix=2
            - id: users-swagger
              uri: ${USER_SERVICE_URL}
              predicates:
                - Path=/v3/api-docs/users
            - id: analyses-swagger
              uri: ${ANALYSIS_SERVICE_URL}
              predicates:
                - Path=/v3/api-docs/analyses
            - id: locations-swagger
              uri: ${LOCATION_SERVICE_URL}
              predicates:
                - Path=/v3/api-docs/locations