spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: users
            uri: http://localhost:8081
            predicates:
              - Path=/api/users/**
            filters:
              - StripPrefix=2
          - id: analyses
            uri: http://localhost:8082
            predicates:
              - Path=/api/analyses/**
            filters:
              - StripPrefix=2
          - id: locations
            uri: http://localhost:8083
            predicates:
              - Path=/api/locations/**
            filters:
              - StripPrefix=2
          - id: users-swagger
            uri: http://localhost:8081
            predicates:
              - Path=/v3/api-docs/users
          - id: analyses-swagger
            uri: http://localhost:8082
            predicates:
              - Path=/v3/api-docs/analyses
          - id: locations-swagger
            uri: http://localhost:8083
            predicates:
              - Path=/v3/api-docs/locations
