server:
  port: 8080

spring:
  application:
    name: skydive-forecast-gateway
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Users Service
        url: /v3/api-docs/users
      - name: Analyses Service
        url: /v3/api-docs/analyses
      - name: Locations Service
        url: /v3/api-docs/locations
  show-actuator: true